name: Deploy to Firebase

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Firebase
        run: |
          npm run build # Adjust this command based on your project setup
          npx firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --non-interactive
